name: AutoPEP8 formatter

on: [push]

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install autopep8
      run: |
        python -m pip install --upgrade pip
        pip install autopep8
    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive **/*.py
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add .
        git commit -m 'Apply autopep8 formatting' || echo 'No changes to commit'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
